export { default as AvatarIcon } from './avatar-icon'
export { default as SearchIcon } from './search-icon'
export { default as PlayIcon } from './play-icon'
export { default as FullScreenIcon } from './fullscreen-icon'
export { default as PauseIcon } from './pause-icon'
export { default as PlayerIcon } from './player-icon'
export { default as SettingsIcon } from './settings-icon'
export { default as VolumeIcon } from './volume-icon'
export { default as PlayerThumbIcon } from './player-thumb-icon'
export { default as SaveIcon } from './save-icon'
export { default as DislikeIcon } from './dislike-icon'
export { default as LikeIcon } from './like-icon'
export { default as ShareIcon } from './share-icon'


// export { default as  } from ''
