export { default as Footer } from './footer/footer'
export { default as Header } from './header/header'
export { default as HeroSection } from './hero-section/hero-section'
export { default as MovieList } from './movie-list/movie-list'
export { default as MoviePlayer } from './movie-player/movie-player'
export { default as Skeleton } from './skeleton/skeleton'
export { default as PageTransition } from './transitions-pages/transitions-pages'